import { Inter } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import "./globals.css";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:"Coverly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <UserProvider>
  
        <body className={inter.className}>
          <Suspense>
            {children}
          </Suspense>
          </body>
      
      </UserProvider>
    </html>
  );
}
